dist: trusty
language: php
php:
  - 7.1
  - 7.2

before_install:
  - composer config -g http-basic.repo.magento.com $MAGE_PUBLICKEY $MAGE_PRIVATEKEY
  - composer install
  - composer create-project --repository=https://repo.magento.com magento/marketplace-eqp magento-coding-standard
  - (cd magento-coding-standard; vendor/bin/phpcs .. --standard=MEQP2 --extensions=php,phtml)
